version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_pritam
      POSTGRES_PASSWORD: postgres_pritam
      POSTGRES_DB: temperature_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
